### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by ChanChar** [ChanChar/TheCharlie#3]
Create the tracking base which will be used to track user actions.

- [ ] Compile a list of current behaviors to track
- [ ] Create a new table for clicks
- [ ] Create the necessary endpoint(s) to handle tracking
- [ ] Create a dashboard to view tracking activity & trends (1 day, 1 week, 1 month, 6 months+)
